seed_everything: 42
trainer:
  accelerator: auto
  strategy: ddp_find_unused_parameters_true #auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: 
    - class_path: lightning.pytorch.loggers.NeptuneLogger
      init_args:
        project: zguo32/CXR-LT-24
        name: fusion, convnext, base, 224, warmup10, lr6e-3, gradient_accumulate8
        log_model_checkpoints: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ..path_to_your_file/save/convnext-base/224/fusion/lr6e-3
        filename: '{epoch:02d}-{val_loss:.4f}-{val_ap:.5f}'
        save_top_k: 6
        monitor: val_loss
        mode: min
    # - class_path: callbacks.submit_callback.SubmissonWriter
    #   init_args:
    #       write_interval: epoch
    #       sample_submission_path: data/sample_submission.csv
    #       submission_path: save/submission.csv        
    #       submission_zip_path: save/submission.zip
    #       submission_code_dir: data/code      
    #       pred_df_path: data/development.csv  
    - class_path: callbacks.fusion_submit_callback.FusionSubmissonWriter
      init_args:
          write_interval: epoch
          sample_submission_path: ..path_to_your_file/test_task1_sample_submission.csv
          submission_path: ..path_to_your_file/tmp1_test_task1_submission_fusion_b224.csv        
          submission_zip_path: ..path_to_your_file/tmp1_test_task1_submission_fusion_b224.zip
          submission_code_dir: ..path_to_your_file/code     
          pred_df_path: ..path_to_your_file/test_task1.csv  
    # - class_path: callbacks.vinbig_pseudo_callback.VinBigWriter
    #   init_args:
    #       write_interval: epoch
    #       vinbig_train_df_path: data/vinbig/train_processed.csv
    #       vinbig_pseudo_train_df_path: data/vinbig/train_processed_pseudo_labeled.csv
    # - class_path: callbacks.nih_pseudo_callback.NihWriter 
    #   init_args:
    #       write_interval: epoch
    #       nih_train_df_path: data/nih/train_processed.csv
    #       nih_pseudo_train_df_path: data/nih/train_processed_pseudo_labeled.csv
    # - class_path: callbacks.chexpert_pseudo_callback.ChexpertWriter 
    #   init_args:
    #       write_interval: epoch
    #       chexpert_train_df_path: data/chexpert/train_processed.csv
    #       chexpert_pseudo_train_df_path: data/chexpert/train_processed_pseudo_labeled.csv
    # - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
    #   init_args:
    #     swa_lrs: 1e-2
    # - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    #   init_args:
    #     monitor: val_ap
    #     mode: max
    #     patience: 10
  fast_dev_run: false
  overfit_batches: 0.0
  val_check_interval: 0.25
  num_sanity_val_steps: 2
  accumulate_grad_batches: 8 #1
  gradient_clip_val: null 
  deterministic: null
  benchmark: true
  max_epochs: 1000
model:
  lr: 8.5e-5 
  stage: fusion 
  single_module_path: ..path_to_your_file/single_model/single_convnext_base_224_model.pth
  classes: 
    - Adenopathy 
    - Atelectasis
    - Azygos Lobe
    - Calcification of the Aorta
    - Cardiomegaly
    - Clavicle Fracture
    - Consolidation
    - Edema
    - Emphysema
    - Enlarged Cardiomediastinum
    - Fibrosis
    - Fissure
    - Fracture
    - Granuloma
    - Hernia
    - Hydropneumothorax
    - Infarction
    - Infiltration
    - Kyphosis
    - Lobar Atelectasis
    - Lung Lesion
    - Lung Opacity
    - Mass
    - Nodule
    - Normal
    - Pleural Effusion
    - Pleural Other
    - Pleural Thickening
    - Pneumomediastinum
    - Pneumonia
    - Pneumoperitoneum
    - Pneumothorax
    - Pulmonary Embolism
    - Pulmonary Hypertension
    - Rib Fracture
    - Round(ed) Atelectasis
    - Subcutaneous Emphysema
    - Support Devices
    - Tortuous Aorta
    - Tuberculosis
  loss_init_args:
    type: asl
    class_instance_nums:
      - 3409
      - 65376
      - 199
      - 4239
      - 74738
      - 168
      - 15371
      - 37256
      - 3661
      - 29628
      - 1169
      - 2803
      - 11568
      - 2965
      - 3986
      - 646
      - 727
      - 10087
      - 778
      - 129
      - 2338
      - 77482
      - 5288
      - 34292
      - 7531
      - 66401
      - 616
      - 3272
      - 704
      - 46660
      - 516
      - 13858
      - 1631
      - 903
      - 8919
      - 172
      - 2046
      - 86079
      - 3336
      - 2078
    total_instance_num: 633025
  timm_init_args:
    num_classes: 0
    model_name: convnext_base.fb_in22k_ft_in1k
    pretrained: true
data:
  dataloader_init_args:
    batch_size: 16
    num_workers: 8            
    pin_memory: true
    persistent_workers: true
  datamodule_cfg:
    stage: fusion #single 
    predict_pseudo_label: null #chexpert
    use_pseudo_label: false #true
    data_dir: ..path_to_your_file/mimic-cxr-jpg/2.0.0/
    train_df_path: ..path_to_your_file/train_labeled.csv
    pred_df_path: ..path_to_your_file/development.csv
    vinbig_train_df_path: data/vinbig/train_processed.csv
    vinbig_pseudo_train_df_path: data/vinbig/train_processed_pseudo_labeled.csv
    nih_train_df_path: data/nih/train_processed.csv
    nih_pseudo_train_df_path: data/nih/train_processed_pseudo_labeled.csv
    chexpert_train_df_path: data/chexpert/train_processed.csv
    chexpert_pseudo_train_df_path: data/chexpert/train_processed_pseudo_labeled.csv
    save_dir: save
    val_split: 0.1
    seed: 42
    size: 1024
    classes:
      - Adenopathy 
      - Atelectasis
      - Azygos Lobe
      - Calcification of the Aorta
      - Cardiomegaly
      - Clavicle Fracture
      - Consolidation
      - Edema
      - Emphysema
      - Enlarged Cardiomediastinum
      - Fibrosis
      - Fissure
      - Fracture
      - Granuloma
      - Hernia
      - Hydropneumothorax
      - Infarction
      - Infiltration
      - Kyphosis
      - Lobar Atelectasis
      - Lung Lesion
      - Lung Opacity
      - Mass
      - Nodule
      - Normal
      - Pleural Effusion
      - Pleural Other
      - Pleural Thickening
      - Pneumomediastinum
      - Pneumonia
      - Pneumoperitoneum
      - Pneumothorax
      - Pulmonary Embolism
      - Pulmonary Hypertension
      - Rib Fracture
      - Round(ed) Atelectasis
      - Subcutaneous Emphysema
      - Support Devices
      - Tortuous Aorta
      - Tuberculosis

ckpt_path:
